name: python Pipeline

on: push

jobs:
  test:
    runs-on: ubumtu-latest
    steps:
     - uses: actions/checkout@v2
     - run: python hello.py
  Build:
    needs: [test]
    runs-on: ubumtu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/upload-artifact@v4
       with:
         name: hello
         path: .
